apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: prod

images:
  - name: gcr.io/env-service-304211/env-producer
    newName: gcr.io/env-service-304211/env-producer
    newTag: 2251945937daea468e115cd0b42a90cd027f9780
  - name: gcr.io/env-service-304211/env-consumer
    newName: gcr.io/env-service-304211/env-consumer
    newTag: 9247f1c9bedb9d704af41765ba2c7d94af54a2a8