apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      run: consumer
  replicas: 1
  template:
    metadata:
      labels:
        run: consumer
    spec:
      serviceAccountName: ksa
      containers:
      - name: consumer
        image: gcr.io/env-service-304211/env-consumer:b9a75ccb6436abc8d19c7473111d54b23e209f53
        envFrom:
          - configMapRef:
              name: infra-config
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
          requests:
            cpu: "0.1"
            memory: "10Mi"