apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo/apps
    repoURL: https://github.com/doitintl/developer-envs
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true